### PR TITLE
Form builder: Bootstrap 5

### PR DESCRIPTION
**Pull request by apepper**
This PR is a bit messy, because it merges the current `master` into `form_builder_master`. The actual changes are only the last three commits. Specifically only the following changed: https://github.com/apepper/scrivito_example_app_js/pull/22/files/665cdff62f1d23aca2146edd775c3cc7fa970cbf..4e1f5080d969f6c538eab96d4405ccf9f815144c?w=1

### CODE REVIEW

**Review by dcsaszar — CHANGES_REQUESTED** [review]
Looks mostly fine.

* [ ] FYI The `popover-body` padding changed from `0.5rem
rem 0.75rem;` to `1rem`, which looks a bit inelegant with little text like "mandatory"
* [x] The popovers no longer disappear when clicking outside. This is bad for multiple reasons:
 * Help bubbles may pile up
 * Help bubbles cover the input which they should provide help for
 * The above requires the user to close the help actively before being able to properly input data

**Comment by agessler** [comment]
@dcsaszar @apepper Fixes https://github.com/agessler/scrivito_example_app_js/commit/a905c39b172bc5eeb1300c68d7b5ca17ab64a489

+ changed placement to `top` instead of `bottom`
+ data trigger is now `hover` instead of `click`... `focus` doesn't work..?
+ popover-body padding is default by framework - you can/will change anyway.. I want it as close as possible to default

**Comment by apepper** [comment]
REVIEW ([b130d86](https://github.com/apepper/scrivito_example_app_js/pull/22/commits/b130d86eaec1e60587db17ceeea8aa6dca6491fc))

**Comment by apepper** [comment]
I briefly tried out "hover" on my iPhone. It works just fine.

**Review by dcsaszar — COMMENTED** [review]
* [x] Mainly good, but there is this cursor position on top of the "mandatory" asterisk (and an even smaller area above the info icon), where the help bubble/help cursor flickers back-and-forth.

**Comment by apepper** [comment]
> [...] but there is this cursor position on top of the "mandatory" asterisk (and an even smaller area above the info icon), where the help bubble/help cursor flickers back-and-forth.

I guess you win the next "eagle eye award":
eagle eye

**Comment by apepper** [comment]
REVIEW ([90249a5](https://github.com/apepper/scrivito_example_app_js/pull/22/commits/90249a56cbcadf2a7618c051129cb7052e238b46))

**Review by dcsaszar — APPROVED** [review]
👍

**Pull request merged**
